### ISSUE TITLE
PWP - Capstone: Tome Rater

### ISSUE THREAD

**Issue by cviddy17** [Rickardo987/Codecademy-Final-TomeRater#1]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Python Code ran Flawlessly. Great job!
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ All project requirements were met. Great job!
 
### Criteria 3: Software Architecture
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Code was written beautifully, however, comments would help make code easier to understand. Class functions were called appropriately.
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Your code fully utilizes Python whenever possible. The next challenge would be list comprehensions in place of for loops!
 
### Overall Score: 16/16
The code you wrote ran flawlessly and was a pleasure to grade. You have a great grasp of Python! Please take the other notes into consideration to improve your code in the future. Great job!

**Comment by Rickardo987** [comment]
Great review!
